### ISSUE TITLE
Why do you input grad & params into metaoptimizer?

### ISSUE THREAD

**Issue by ethancaballero** [ikostrikov/pytorch-meta-optimizer#6]
In line 81 & 135 of meta_optimizer.py
Why do you input grads & params (and loss as well in line 135) into metaoptimizer?

Did you try with & without, and one version worked better? In 1606.04474, they seem to just input grads into metaoptimizer.

**Comment by ikostrikov** [comment]
Hi @ethancaballero, I was hard to reproduce results from meta optimizer papers so at some point I just gave up and shared this code just as an example of how it can be implemented in PyTorch.

Meta optimizers are very slow so I didn't validate any design decisions properly.
